### ISSUE TITLE
Support for geo-types

### ISSUE THREAD

**Issue by msvbg** [tirithen/clipper2#5]
Hi, cool project!

I discovered this when searching for Rust bindings to Clipper 2. I'm stuck on Clipper 1 via [geo-clipper](https://github.com/lelongg/geo-clipper) which uses a five year-old version of the library, and while it works I'm curious to see if Clipper 2 is more numerically robust.

One thing I'd like to see is integration with [geo-types](https://github.com/georust/geo/tree/main/geo-types/src) since my code is already using these types all over the place, and I might (at some point) send a PR for this myself if you'd be open to it.

**Comment by msvbg** [comment]
I've now started PR-bombing you instead! I think the types in this package can do all I need if I can just add a few more bells and whistles.

**Comment by tirithen** [comment]
Hi @msvbg ! Thank you for the interest in the project, and thank you for the merge requests! 

I also found the existing Clipper 1 one libraries for Rust insufficient for my purposes, hence it took me down the road of learning Rust FFI, eventually it started to work out. I'm mainly using it for generate CNC cut paths for my [cnccoder](https://crates.io/crates/cnccoder) crate, great to see some other uses of clipper2.

I like that your suggestions does not add specific dependencies to external crates (except for serde with an optional feature which is reasonable). If you can get your geo-types integration that way it keeps the clipper2 crate agnostic for those that uses it for other purposes.

In general it looks great, but I have some thoughts on possibly some more testing for the new additions, formulate the commit messages according to [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) so that the change log generation will work, and also I'm thinking about the signature change of the .scale method from only a single scale value to x/y. Maybe we could add a separate .scale_xy method or similar for that use case? Anyhow, I'll review them one by one and add some comments.

**Comment by tirithen** [comment]
Oh, and if you then want more direct integration/conversion to the specific geo-types crate it might be better to put that code in a separate crate. This should remove the need to make major/breaking releases of the crate if the geo-types crate that has not yet reached version 1 makes breaking changes.

I think that clipper2 will be more flexible if it in general focuses in implementing conversions to/from basic core types such as Vec<[f64; 2]> and similar rather than conversions to specific types inside other crates that might change over time. This should keep clipper2 flexible and fairly easy to integrate into various other projects.

Do you have any thoughts on this?

**Comment by msvbg** [comment]
geo-types uses a slightly different representations for polygons than Clipper2, and I figured it's wasteful and maybe error-prone to convert back and forth between them. I'd prefer to stick to one representation, and I don't really need anything that Clipper2 doesn't already provide, so my current plan is to just remove my dependency on geo-types entirely.

> In general it looks great, but I have some thoughts on possibly some more testing for the new additions, formulate the commit messages according to [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) so that the change log generation will work, and also I'm thinking about the signature change of the .scale method from only a single scale value to x/y. Maybe we could add a separate .scale_xy method or similar for that use case? Anyhow, I'll review them one by one and add some comments.

Sure, I can do another pass on these PRs and update them accordingly

**Comment by tirithen** [comment]
Sounds good! I'm finishing up the PRs on clipper2c-sys now and make another release of that crate, should make finishing the clipper2 PRs easier. I need to finish for the day soon, but I'll keep an eye on the other PRs a bit later tomorrow.

**Comment by msvbg** [comment]
I’m a somewhat afk today but will get to this tomorrow or over the weekend

**Comment by tirithen** [comment]
I merged your requests now, thanks for the contribution. The new features are available as version 0.3.0.

I made some minor changes, mostly around testing, but also the scale_around_point will now consider the paths as a "group" and scale them all together rather than as individual paths.

Feel free to open a new issue if I got it wrong in any way.
